<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TickTest.ServiceDefaults\TickTest.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Data.TickTest\Domain.MarketData.csproj" />
    <ProjectReference Include="..\Application.MarketData\Application.MarketData.csproj" />
    <ProjectReference Include="..\Infrastructure.MarketData\Infrastructure.MarketData.csproj" />
  </ItemGroup>

</Project>
